name: colibri_noticias
description: "Projeto de Notícias específicas de Santa Teresa"
version: 1.0.0+1

environment:
  sdk: ^3.7.0-209.1.beta

dependencies:
  flutter: 
    sdk: flutter
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  brasil_fields: ^1.15.0
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.3.1
  gradient_borders: ^1.0.1
  shared_preferences: ^2.5.2
  font_awesome_flutter: ^10.8.0
  http: ^1.4.0
  timezone: ^0.10.1
  firebase_core: ^3.15.1
  cloud_firestore: ^5.6.11
  firebase_auth: ^5.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.8
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/imagens/logo.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/imagens/logo.png
  android: true
  ios: true
  web: true

flutter:
  uses-material-design: true
  assets: 
    - assets/imagens/